version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000" # PHP-FPM

    web:
        image: nginx:alpine
        container_name: laravel-web
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: laravel-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
    adminer:
        image: adminer
        ports:
            - 8081:8080
